### PR TITLE
Fixed makefiles in some Swift templates

### PR DESCRIPTION
**Pull request by Luki120**
What does this implement/fix? Explain your changes.
---------------------------------------------------
* Title

Does this close any currently open issues?
------------------------------------------
https://github.com/theos/theos/issues/778

Any relevant logs, error output, etc?
-------------------------------------
*

Any other comments?
-------------------
*

Where has this been tested?
---------------------------
**Operating System:** Ubuntu 22.04

**Platform:** WSL 2

**Target Platform:** …

**Toolchain Version:** …

**SDK Version:** …

### CODE REVIEW

**Review by L1ghtmann — COMMENTED** [review]
Makefile change seems fine but am unsure about the deployment target change. According to Apple, Swift projects can be deployed as [far back as iOS 7](https://developer.apple.com/swift/blog/?id=2). We account for the variations in lib compatibility through the control files:' depends
https://github.com/theos/templates/blob/e55f63be02a61edd5d2b201fdfa6d9d62bfafa85/ios/application_swift/control#L9
https://github.com/theos/templates/blob/e55f63be02a61edd5d2b201fdfa6d9d62bfafa85/ios/tweak_swift/control#L9
https://github.com/theos/templates/blob/e55f63be02a61edd5d2b201fdfa6d9d62bfafa85/ios/tool_swift/control#L10
The only exception to this is SwiftUI App as its deployment target is > iOS 12.2.

**Comment by Luki120** [comment]
I answered on [Discord](https://discord.com/channels/811490080278839327/811494949849661490/1245869288796196935) but I'll leave my comments here so anyone can see.

I'm not sure why it'd fail when the deployment is set to 7.0 if it's supported. Maybe newer toolchains broke it somehow, but it does fail. The error is the same as this one https://github.com/theos/theos/issues/778, after these changes, `test.sh` is able to build all the templates successfully, so this PR should close that issue.
The rest of the Swift templates I didn't modify, all have 12.2 as the mininum deployment target:
https://github.com/theos/templates/blob/e55f63be02a61edd5d2b201fdfa6d9d62bfafa85/ios/preference_bundle_swift/Makefile#L1
https://github.com/theos/templates/blob/e55f63be02a61edd5d2b201fdfa6d9d62bfafa85/ios/tweak_swift/Makefile#L1

**Comment by Luki120** [comment]
I read that thread and did further testing to see if it was sdk related or not, it's a mix of both, here are my findings:

Building with 16.5 & 13.7 with deployment target set to 7.0 throws a similar error to the one that person had:
```bash
error: emit-module command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: unable to load standard library for target 'armv7-apple-ios7.0'

==> Compiling module interface (arm64)…
error: fatalError
make[4]: *** [/home/luki120/theos/makefiles/instance/rules.mk:363: internal-swift-applicationswift-armv7] Error 1
make[3]: *** [/home/luki120/theos/makefiles/instance/rules.mk:372: /home/luki120/templates/build/applicationswift/.theos/obj/debug/armv7/.swift-stamp] Error 2
```

Building with 15.6 & 14.5 throws this error instead, again with deployment of 7.0:
```bash
<unknown>:0: error: IR generation failure: Cannot read legacy layout file at '/home/luki120/theos/toolchain/linux/iphone/lib/swift/iphoneos/layouts-armv7.yaml'
```

Now, building with 16.5, 15.6 & 14.5 with a deployment of 12.2 goes through ✅
However, building with 13.7 & a deployment of 12.2 doesn't ❌

We can conclude that:
* A higher deployment version is needed so that the build doesn't fail in every scenario
* An sdk newer than 13.7 is needed as well

**Comment by L1ghtmann** [comment]
Hm, interesting. Thanks for looking into it. I'm not too familiar with the Swift setup and what makes so I'll leave this for others to comment on.

**Comment by leptos-null** [comment]
This error appears to be caused by attempting to load

```
$(SYSROOT)/usr/lib/swift/Swift.swiftmodule/armv7-apple-ios.swiftinterface
```

which does not exist in recent SDKs.

Adjusting the deployment target to `12.2` makes this error go away because Theos defaults the `ARCHS` to not include `armv7` above `11.0`.

From Luki's comment, it sounds like new toolchains are not compatible with SDKs older than 14 (`< 14`).

I think adjusting the deployment target for templates that use swift to `11.0` makes sense.

The other option that I think is reasonable is to keep `7.0` as the deployment target and specify `ARCHS` instead. I would rather theos (makefiles) pick the `ARCHS` (as it already does now), so my preference is the first option.

**Review by leptos-null — APPROVED** [review]
Using `12.2` makes sense to me for the deployment target in the Swift templates.
As Luki pointed out, the other Swift templates use `12.2` as the deployment target. Kabir confirmed he choose the version because `12.2` is the first iOS version where [Swift libraries are included](https://github.com/theos/theos/blob/1f2a86052417dd8ec66f0604c5aef250ecb808af/makefiles/targets/_common/iphone.mk#L33) in iOS.

Verified `.nic.tar` files match source.

**Pull request merged**
