### PR TITLE
Use INSTALL_TARGET_PROCESSES in Makefile

### PR DESCRIPTION
**Pull request by leptos-null**
As per #2 (mark 5): "Make templates use ... INSTALL_TARGET_PROCESSES to kill processes instead of adding the rule at the bottom."

### CODE REVIEW

**Comment by uroboro** [comment]
Thanks for working on this. Can you change it a bit so as to place `@@KILL_PROCS@@` after the last variable and treating it as a list?

Taking the tweak example:

```makefile
include @@THEOS@@/makefiles/common.mk

TWEAK_NAME = @@PROJECTNAME@@
@@PROJECTNAME@@_FILES = Tweak.xm

include $(THEOS_MAKE_PATH)/tweak.mk
```

It would become:

```makefile
include @@THEOS@@/makefiles/common.mk

TWEAK_NAME = @@PROJECTNAME@@
@@PROJECTNAME@@_FILES = Tweak.xm
INSTALL_TARGET_PROCESSES = @@KILL_PROCS@@

include $(THEOS_MAKE_PATH)/tweak.mk
```

**Comment by leptos-null** [comment]
> place @@KILL_PROCS@@ after the last variable

Yes, I'll do that. 

An afterthought: Would `@@PROJECTNAME@@_INSTALL_TARGET_PROCESSES` work/be preferable? I'm not as familiar with `make`: [ref](https://github.com/theos/theos/blob/master/makefiles/package.mk#L127)

> treating it as a list

I do not think I understand, sorry. Does perl have an array indicator, that which I am not using? I tested this PR by listing multiple processes in NIC (`mediaserverd backboardd locationd`), and it worked as expected: [ref](https://github.com/hbang/TypeStatus/blob/master/Makefile#L7)

**Comment by kirb** [comment]
Note due to the ifeq I use to check INSTALL_TARGET_PROCESSES is non-empty, it has to be set before including common.mk. I could change that to be tested using a shell `if [[` as well as maybe adding a per-instance var as a feature.

**Comment by uroboro** [comment]
At the time I was not aware that the check happened in common.mk. I apologize for the confusion.

**Comment by leptos-null** [comment]
No reason for apologies, I feel this was a productive discussion. If I may recommend, as @kirb mentioned, I think the variable should be a "per-instance var", as he described- similar to the `CODESIGN_FLAGS` variable.

**Comment by kirb** [comment]
Merged via rebase in 48854f2, moved the `@@KILL_PROCS@@` back to the top. Thanks!

**Pull request closed without merging**
