### PR TITLE
Add sideload template to create tweaks for non-jailbroken devices without theos-jailed

### PR DESCRIPTION
**Pull request by iMokhles**
source of my tweak_sideload template

### CODE REVIEW

**Comment by kirb** [comment]
Two issues:

This is quite opinionated, for instance here: https://github.com/iMokhles/nicTemplates/blob/9e022b10df185d3b800a0376fd18bca4d5dba6cc/ios/tweak_sideload/Makefile#L1-L4 Templates should only override Theos defaults where necessary for the project to work.

And second, I don’t think this is within the scope of Theos itself. Are you aware of [theos-jailed](https://github.com/kabiroberai/theos-jailed)? It’s a Theos module that provides support for building tweaks for packaging in an ipa. It seems you’re pretty much trying to achieve a basic version of the same functionality?

**Comment by iMokhles** [comment]
I uses this templates since I released first side load tweaks here 
https://github.com/iMokhles/Tweaks-for-SideLoaded-Apps I don't try to achieve basic version of theos-jaild,  my setup is completely different, and for the override Theos defaults I used to do it like that but I can will remove it.

and about if this within the scope of theos itself or not, Theos is `( A cross-platform suite of tools for building and deploying software for iOS and other platforms. )` so it's not restricted to jailbroken devices only it's a building software and with my template developers can build their code which wrote before for jailbroken devices easily by using my template or applying the same defaults for 
```
TWEAKNAME_LOGOSFLAGS = -c generator=internal
TWEAKNAME_INSTALL_PATH = @executable_path
```

**Comment by kirb** [comment]
I get your point, but we don’t want Theos to grow to have so many features that it’s too hard to support them all. (This is already kind of the case really with the number of platform/target combinations we support.) And additionally this is rather barebones; just “installing” by copying the dylib to a slightly more obvious spot; not taking into account resources it might need; not packaging into an ipa for testing, etc. Theos needs to support the entire build process from compilation to packaging and installation. People will use this template, run `make do`, and think, “now what?”. At that point, if you add those features you’re basically reinventing theos-jailed, and I don’t see any utility in us supporting two versions of the same-ish thing.

**Comment by iMokhles** [comment]
got what you mean, but I don't agree with the fact it's reinventing `theos-jailed` because `theos-jailed `uses a lot of scripts and uses `CydiaSubstrate, Cycript` etc to get the `dylib` works on non-jailbroken device, my template uses the mentioned flags only to get the current `theos` project works on non jailbroken devices, and about injecting the dylib into apps yeah it's annoying to do it manually but it's the best way to make it easy to compile the same project for ( `jailbroken and non-jailbroken `) without extra scripts and tools and developers can do the injection manually if they want, 

and again this template doesn't have anything to do with theos-jailed means there are no 2 versions of theos or thees-jailed etc, it's the same theos just adding the magic defaults flags which make the current code works on non-jailbroken devices

**Comment by kirb** [comment]
Cycript is only for convenience during debugging; Substrate is highly recommended over the traditional/`internal` approach anyway as there are some shortcomings that it solves. You’re saying this lets you do it “without scripts and tools”, but you need some sort of build system anyway (even if different from theos-jailed’s; even if not part of Theos) or you’re forced to build and install an ipa manually every time.

Again, I’m not sure what this solves, and it creates more problems with its simplicity. I’m going to close this because ultimately it needs a lot of work, and some functionality added to Theos either directly or via a module, to be at a point that we can consider supporting it. (Use what works for you, of course, and feel free teach others about this if they ask you about it. We just can’t support it as an official feature as it stands.)

**Comment by iMokhles** [comment]
👍

**Pull request closed without merging**
